### ISSUE TITLE
confirm fork and edit repo in "Help improve this page"

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-wcag-supplemental#24]
Which repo and file should the fork link on each page go to as some of the content source is in this repo and some in the coga repo but converted to the content here with the generate script.

**Comment by shawna-slh** [comment]
Steve and Shawn agreed to this repo. Document that changes to COGA need to be done at the source.

**Comment by SteveALee** [comment]
I suggest leaving modifying the scripts so the files contain `github-src` and `github` in frontmatter

Possibly `github` entry can be defined in jeckyll config file rather than each file.
