### ISSUE TITLE
Finalise All WCAG Guidance page (for EC project)

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-wcag-supplemental#27]
This provide nav between the various new WAI GUIDE projectpages new pages (D1.1)

- Techniques / Understanding previewe: https://draft-wcag-redesign.netlify.app/techniques/, https://draft-wcag-redesign.netlify.app/understanding. final TBD
- COGA / Supplemental Guidance preview: https://wai-wcag-supplemental.netlify.app/wcag-supplemental/supplemental-guidance/ 
- ACT Rules preview: https://deploy-preview-51--wcag-act-rules.netlify.app/standards-guidelines/act/rules/ 

Latest draft: https://deploy-preview-101--wai-intro-wcag.netlify.app/standards-guidelines/wcag/docs/

**Comment by shawna-slh** [comment]
added to https://github.com/w3c/wai-wcag-supplemental/issues/31
