### ISSUE TITLE
All / List of all

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supplemental#32]
Decide approach - consider At a Glance approach - and [Summary in TR](https://www.w3.org/TR/coga-usable/#summary)

*ALSO* considering Low Vision coming, hopefully...

**Comment by SteveALee** [comment]
Changed top level headings to list and hid the marker.  See [preview](https://619622708365e0000810ef64--wai-wcag-supplemental.netlify.app/wcag-supplemental/supplemental-guidance/)

The `+` next to each item can be hidden too but I think it is useful
