### ISSUE TITLE
Indicate links out of this design

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supplemental#43]
There are links under “Related Information” that go to /TR/.  I think _either_:
* Put a sentence under the “Related Information” heading something like “The links below go to a section of Making Content Usable for People with Cognitive and Learning Disabilities in a different format.”<br>_or_
* Put icon after each link. Here is the icon for links that go to a different section of the W3C website: https://wai-website-theme.netlify.app/components/icons/#different-view

**Comment by SteveALee** [comment]
I went for the icon as that seems clearer
