### ISSUE TITLE
"All Supplemental Guidance" in main nav background on that page

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supplemental#46]
When on an "All..." or "About..." page, in the main nav, that page should have the light background of the main body. For example: 
![image](https://user-images.githubusercontent.com/6991814/151368737-e42dec10-b1db-41a6-b3e4-a0323b9c1f1e.png)

But that's not working on the All page:
![image](https://user-images.githubusercontent.com/6991814/151368859-d63953ff-3491-4344-94e5-67ea1e49b255.png)

It is on the All Rules page: 
![image](https://user-images.githubusercontent.com/6991814/151369036-0afdcf08-9913-4784-81c8-d9aabb2d53d3.png)

**Comment by SteveALee** [comment]
hhm, odd. Thanks for the working example of ACT Rules to compare against

**Comment by SteveALee** [comment]
Extra trailing slash on page.ref meant it did not match current page.ref
