### ISSUE TITLE
Meeting user needs with redesign

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supplemental#48]
Hey @SteveALee 

I spent a lot of time going over [analysis](https://github.com/w3c/wai-wcag-supporting-documents-redesign/wiki/Requirements-Analysis), [user flows](https://github.com/w3c/wai-wcag-supporting-documents-redesign/wiki/Current-user-flows), and [UI considerations](https://github.com/w3c/wai-wcag-supporting-documents-redesign/wiki/UI-considerations). And going over user feedback from EOWG and COGA TF. I basically went back to the drawing board. I know that's annoying at this stage; however, none of the prototpyes from the last year were meeting user needs.

Here's a draft different approach that I think better meets user needs:
![image](https://user-images.githubusercontent.com/6991814/152882085-acba6d26-5406-4769-af72-3d4533b7c281.png)

Let's talk Tuesday about getting user feedback on this before you spend much effort on re-coding.

Thanks for your patience and perseverance!!!

**Comment by SteveALee** [comment]
My initial (printable) reactions are

- Yes to breadcrumbs as:
  - provide better integration to the rest of the site
  - are a coga design pattern
- having interpage nav all together at top and not with intra page nav is a good thing. But uses unfamiliar terms?
- those arrows really stand out for me, in a bad way. A good idea just need some stylistic attention?
- can we use the side bar for more than page nave. Just a thought, I prefer the simplicity as it is.

**Comment by shawna-slh** [comment]
Thanks for the discussion earlier, @SteveALee. Here are the things that are different from previous version:
* [ ] Banner/header adds explanatory blurb “Additional ways to improve accessibility (not required to meet WCAG)” italicized and not bold. {tie-in: main WAI site has tagline in banner/header also italic and not bold.}
* [ ] Add faux breadcrumb in nav bar. {tie-in: main WAI site has breadcrumbs. And users really wanted them!}
  * Note the different view icons after the first three.
  * For now, this can be the same on all pages. (When there is low vision stuff, then we’ll need to tweak a bit.)
  * Ideally when on one of the latter two pages, then it’s not a link. I think OK to leave that for an enhancement later and not spend time on it now.
* [ ] put objective & design pattern navigation in the main top nav bar.
  * Those [icons are from here](https://wai-website-theme.netlify.app/components/icons/#all-icons). Maybe just making them smaller will be enough for now? We could put as low priority to redesign them.
* [ ] Page Contents box
  * [ ] same style as main site https://wai-website-theme.netlify.app/components/boxes/#default-box for the overall box
   * [ ] then the new CSS with separator lines instead of bullets
   * [ ] Page Contents box in DOM after the h1

optional
* [ ] Try the cognitive icon top right of h1 like the [media resource](https://www.w3.org/WAI/media/av/users-orgs/) I think we want [this lighter one](https://github.com/w3c/wai-wcag-supplemental/blob/main/content-images/wai-wcag-supplemental/icon-brain-green-transparent.svg)

Let me know if you have other idea or questions or I missed anything.

THANKS, Steve!!!

**Comment by SteveALee** [comment]
> Page Contents box in DOM after the h1

difficult due to CSS grid - needs significant layout rework

**Comment by shawna-slh** [comment]
Hey @SteveALee Thanks for trying the true breadcrumb and other options after input from COGA folks. The approach below:
* puts what newbies need in the main header and has some similarities to the main WAI website header
* puts the in-resource navigation in the light blue area, similar to the tools design

Perhaps that will be good for Phase 1 and fairly easy to implement !?!

![image](https://user-images.githubusercontent.com/6991814/153503329-44b46a3a-a8ec-4cbd-baa3-a58f90620d00.png)

**Comment by shawna-slh** [comment]
* COGA TF minutes 3 Feb 2022
* [EOWG minutes 4 Feb 2022](https://www.w3.org/2022/02/04-eo-minutes#t02)
* COGA TF minutes 10 Feb 2022
* [EOWG minutes 11 Feb 2022](https://www.w3.org/2022/02/11-eo-minutes)

**Comment by SteveALee** [comment]
Yes, I like it as it gets round the previous Coga TF feedback. Also clearly separates the Nav from the paging controls.

- maybe have a darker blue under the nav. to separate it form the header like the Main site does. But some how  make it a little different to indicate in a different area?
- All -> "All Cognitive Patterns"?

**Comment by SteveALee** [comment]
@shawna-slh 

please see https://wai-wcag-supplemental.netlify.app/wcag-supplemental/about

Note I have a slight concern that the two boxes here look too similar

![image](https://user-images.githubusercontent.com/618922/153592989-d775f9fb-6216-4120-bb8d-4679be4d959a.png)

**Comment by shawna-slh** [comment]
> Note I have a slight concern that the two boxes here look too similar
for the record, we changes that to match how they're used elsewhere on the WAI site.
