### ISSUE TITLE
COGA page titles

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supplemental#54]
Hey @SteveALee 

I just noticed title:
> <title> Break Media into Chunks | Web Accessibility Initiative (WAI) | W3C</title>

I think we need to change that. I'll think fresh in the morning...

**Comment by SteveALee** [comment]
Ah, yes I was thinking about checking how the page title matched the H1 Heading when working on the new minimal header. And then I forgot. :)
